org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
# AGP 8.5.x da R8 full-mode ConcurrentModificationException beradi — o'chirilgan.
# Shrink/minify baribir yoqilgan (app/build.gradle.kts).
kotlin.incremental=true
